name = "Vlasov"
uuid = "2b4e4dc6-bb65-44a8-9970-a8d90b7ff1a4"
version = "0.1.0"
authors = ["Laurent Plagne <laurent.plagne@gmail.com>"]

[deps]
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[weakdeps]
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"

[extensions]
VlasovMetalExt = "Metal"

[compat]
BandedMatrices = "1.12.0"
KernelAbstractions = "0.9.42"
LinearAlgebra = "1.12.0"
Metal = "1.11.0"
SpecialFunctions = "2.9.0"
julia = "^1"

[extras]
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Metal", "Test"]
