"""
The two mean-field terms which, added to the Hartree potential, make the
cluster: the electrons' exchange-correlation among themselves, and the
attraction of the ionic background.

Without them there is no cluster, only an electron gas repelling itself apart.
The Fortran added them in `pspech`, called at every step before the force
computation — the name suggests a diagnostic, which it is far from being.
"""

"Wigner-Seitz radius of sodium, in atomic units (the Fortran's `rs`)."
const WIGNER_SEITZ_NA = 4.0

"""
    Jellium(nions; rs = WIGNER_SEITZ_NA)

Ionic background modelled by a uniformly charged sphere of `nions` positive
charges, of radius `r₀ = rs·N^⅓`.

It is this background that holds the electrons in; its density is that of a
metal of Wigner-Seitz radius `rs`.

`rs` is a keyword, and not a second positional argument, so as not to compete
with the `Jellium(nions, radius)` constructor generated by the type declaration
— which, carrying the constraint `T<:AbstractFloat`, is more specific than a
`where {T}` and would silently win.
"""
struct Jellium{T<:AbstractFloat}
    nions::T
    radius::T
end

function Jellium(nions::Real; rs::Real = WIGNER_SEITZ_NA)
    T = float(promote_type(typeof(nions), typeof(rs)))
    Jellium{T}(T(nions), T(rs) * cbrt(T(nions)))
end

"""
    uniform_sphere_potential(Q, R, r) -> T

Potential created by a ball of radius `R` carrying the charge `Q` uniformly, at
distance `r` from its centre — up to sign, the one felt by an opposite charge.

    r ≥ R :  −Q/r                      (as for a point charge)
    r < R :  −Q·(3 − (r/R)²) / 2R      (parabolic, finite at the centre)

Two objects of the model have this shape, and that is no coincidence: the
jellium background, and the **softened projectile**, whose charge is
deliberately spread over a ball of radius `cutoff` so that head-on collisions
are not singular.
"""
@inline function uniform_sphere_potential(Q, R, r)
    r < R ? -Q * (3 - (r / R)^2) / 2R : -Q / r
end

"""
    potential(jel, r) -> T

Potential of the jellium background at distance `r` from the centre.
"""
@inline potential(jel::Jellium, r) = uniform_sphere_potential(jel.nions, jel.radius, r)

# Constants of the LDA exchange-correlation potential, in atomic units.
# Dirac exchange: Vx = −(3/π)^⅓ ρ^⅓.
# Gunnarsson-Lundqvist correlation: Vc = −0.0333·ln(1 + 11.4/rs),
# with 1/rs = (4π/3)^⅓ ρ^⅓.
const XC_EXCHANGE = -cbrt(3 / π)
const XC_CORRELATION = -0.0333
const XC_CORRELATION_SCALE = 11.4 * cbrt(4π / 3)

"""
    xc_potential(ρ) -> T

LDA exchange-correlation potential for an electron density `ρ`.

Exchange takes Dirac's form, correlation Gunnarsson-Lundqvist's. Both depend on
the density only through `ρ^⅓`, computed once.
"""
@inline function xc_potential(ρ::T) where {T}
    c = cbrt(ρ)
    T(XC_EXCHANGE) * c + T(XC_CORRELATION) * log1p(T(XC_CORRELATION_SCALE) * c)
end

"""
    xc_energy_density(ρ) -> T

LDA exchange-correlation energy density — not to be confused with
[`xc_potential`](@ref), which is its functional derivative.

This is the second loop of `pspech2`: exchange carries Dirac's ¾ factor, and
correlation takes Gunnarsson-Lundqvist's **integrated** expression,

    εc = −0.0333·[(1+x³)·ln(1+1/x) + x/2 − x² − ⅓],   x = rs/11.4

instead of the potential's plain logarithm. The energy budget calls for `ε`, the
forces call for `V`; confusing the two is the mistake this pair of functions
exists to make visible.
"""
@inline function xc_energy_density(ρ::T) where {T}
    ρ <= 0 && return zero(T)
    x = cbrt(3 / (4 * T(π) * ρ)) / T(11.4)
    T(XC_EXCHANGE) * cbrt(ρ) * 3 / 4 +
        T(XC_CORRELATION) * ((1 + x^3) * log1p(1 / x) + x / 2 - x^2 - T(1) / 3)
end

"""
    effective_potential!(csol, ρ, mesh, jellium) -> csol

Adds exchange-correlation and the jellium background to the Hartree potential —
already present in `csol` as spline coefficients (the Fortran's `pspech`).

Both terms are evaluated at the collocation points, then converted to
coefficients before being added: that is the space `csol` lives in, and mixing
the two would be exactly the silent bug the type distinction exists to prevent.
"""
function effective_potential!(csol::Array{T,3}, ρ::Array{T,3},
                              mesh::SplineMesh{3,T}, jel::Jellium{T}) where {T}
    gx, gy, gz = map(ax -> ax.colloc, mesh.axes)
    extra = mesh.scratch[1]
    # ⚠️ This loop long carried a comment saying it must **not** be parallelised:
    # measured, the parallel version was then 0.93 times as fast, that is,
    # slower. That was true, and it no longer is: the slowdown came from
    # OpenBLAS's thread pool, contending for the processor with the
    # `Threads.@threads` loops. Under Accelerate there is no such pool, and the
    # same loop gains **×5** — with bit-identical results. A performance
    # decision is only valid in the environment where it was measured.
    Threads.@threads for k in eachindex(gz)
        @inbounds for j in eachindex(gy), i in eachindex(gx)
            r = sqrt(gx[i]^2 + gy[j]^2 + gz[k]^2)
            extra[i, j, k] = xc_potential(ρ[i, j, k]) + potential(jel, r)
        end
    end
    csol .+= spline_coefficients!(mesh.scratch[2], extra, mesh)
end
